steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/recipevision-402518/recipevision', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/recipevision-402518/recipevision']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'recipevision-service', '--image', 'gcr.io/recipevision-402518/recipevision', '--region', 'us-west2']

images:
  - gcr.io/recipevision-402518/recipevision
